### PR TITLE
Fix #39 - Use persisted info as session attributes for setting stop ID

### LINKED ISSUE #39: Trying to update stop ID with or without values resets skill
**Steps to reproduce:**

1.  Go through the initial bootstrap of setting up your city and stop number
1.  Say "Alexa, ask OneBusAway to set my stop"
1.  Say your new stop number when prompted

or:

1.  Go through the initial bootstrap of setting up your city and stop number
1.  Say "Alexa, ask OneBusAway to set my stop to X"

**What happens:**

Alexa says "Welcome to OneBusAway! Let's set you up..."

**What I expect:**

My stop number should be updated, and Alexa should confirm with "Ok, your stop number is %s in the %s region...".

**Cause:**

Looks like this happens because we're expecting the `CITY_NAME` session variable to be set in `setStopNumber()`, as in the initial bootstrap flow.  But, when we're coming in via `onIntent()` for `SetStopNumberIntent` without an existing session, we don't have this session variable set.  So, looks like we need to check the persisted user record for an existing `CITY_NAME`.  This blurs the line a bit between the Anon and AuthedSpeechlets, and we need to figure out the best way to handle it.

@philipmw Thoughts?

### PR DESCRIPTION
**Pull request by barbeau**
@philipmw Please take a look.

### CODE REVIEW

File: src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java [hunk 1]
```diff
@@ -73,6 +74,7 @@ public SpeechletResponse onIntent(final IntentRequest request,
                             userData.getCity(), userData.getRegionName()));
             return SpeechletResponse.newTellResponse(out);
         } else if (SET_STOP_NUMBER.equals(intent.getName())) {
+            populateAttributes(session);
```
Comment (philipmw) [inline src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java]: I think AuthedSpeechlet should `populateAttributes` always, rather than just in this branch. That'll make it easier for us to reason about session attributes.

Comment (barbeau) [inline src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java]: Agreed - I just force-pushed a new commit into this PR that moves `populateAttributes()` to the top of the `onIntent()` method, so the session will always contain the latest persisted user data.

**Comment by philipmw** [comment]
And you boosted code coverage!

**Comment by barbeau** [comment]
:+1: :).  I'm still getting used to JMockit - do you have any good pointers to resources for learning it?

**Comment by philipmw** [comment]
I've been using the official documentation, which is decent. Still, lots of intuition and trial-and-error required.
